name: LaTeX PDF Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PDF from LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex  # This is what gets compiled

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf  # The output file from latexmk
